name: MySQL Docker Workflow

on:
  workflow_dispatch:

jobs:
  run-mysql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Pull MySQL image
      run: docker pull mysql:latest

    - name: Run MySQL container
      run: |
        docker run --name drilondb -e MYSQL_ROOT_PASSWORD=root -d mysql:latest

    - name: Verify MySQL container is running
      run: docker ps -a
